### ISSUE TITLE
Demo unaccessible

### ISSUE THREAD

**Issue by alesaccoia** [UseAllFive/StreetviewSequence.js#5]
Getting an alert that says: "This page was unable to display a Google Maps element. The provided Google API key is invalid or this site is not authorized to use it. Error Code: InvalidKeyOrUnauthorizedURLMapError"

**Comment by jamesinealing** [comment]
Same for me. Is this project still active? Should it work with a correct key, or is it something more fundamental like a change at Google that has broken it permanently?

EDIT: having just tried a local installation I can confirm that it does work with a valid API key
